# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ master ]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
    - name: ssh-to-server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            echo $'\n' "------ ruige reload  -------------------" $'\n'
            docker stop ruige
            docker rmi ruige
            docker build -f ~/docker_ruige/Dockerfile --force-rm --no-cache -t ruige ~/docker_ruige/
            docker run --rm -d -p3001:3001 --name ruige ruige
            echo $'\n' "------ CODE READY SUCCESSFUL!!! ---------" $'\n'
